---

- name: ensure it is known this is a google system
  file:
    path: /etc/google_system
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: install google guest environment packages
  zypper:
    update_cache: yes
    name: "{{ item }}"
    state: installed
  with_items:
    - google-guest-agent
    - google-guest-configs
    - google-guest-oslogin
    - google-osconfig-agent

- name: Setup Daemons
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    masked: "{{ item.masked | default(false) }}"
  with_items: "{{ services_google }}"

- name: stub out network interface configuration files
  copy:
    src: files/etc/sysconfig/network/ifcfg-eth
    dest: "/etc/sysconfig/network/ifcfg-eth{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ range(0, 10 + 1, 1)|list }}"

- name: move gcp sysctl files into place
  copy:
    remote_src: yes
    src: /srv/cray/sysctl/google/
    dest: /etc/sysctl.d/

- name: schedule job to ensure /root/.ssh/authorized_keys file is our /root/.ssh/id_rsa.pub only every 1 minute
  cron:
    name: "gcp authorized keys"
    minute: "*/1"
    job: "cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys >> /var/log/cray/cron.log 2>&1"
